version: "3.2"
services:
  redis:
    image: redis:alpine3.17
    container_name: redis
    privileged: true
    volumes:
      - /workspace/service/redis/db:/data:rw
    #  - D:\workspace\service\redis\conf\redis.conf:/usr/local/etc/redis/redis.conf:rw
    ports:
      - 6379:6379
    restart: always
    #command: /usr/local/etc/redis/redis.conf
    networks:
      hss-network:
        aliases:
          - redis
  emqx:
    image: emqx:5.0.21
    container_name: emqx
    privileged: true
    #volumes:
    #  - D:\workspace\service\redis\db:/data:rw
    #  - D:\workspace\service\redis\conf\redis.conf:/usr/local/etc/redis/redis.conf:rw
    ports:
      - 11883:11883
      - 18083:18083
      - 1883:1883
      - 4370:4370
    restart: always
    networks:
      hss-network:
        aliases:
          - emqx
  nginx:
    image: nginx:latest
    container_name: nginx
    privileged: true
    volumes:
      - /workspace/wwwroot/hss-web:/var/www/hss/dist:rw
      - /workspace/wwwroot/byzt:/var/www/byzt:rw
      - /workspace/service/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:rw
      - /workspace/service/nginx/conf/vhosts/:/etc/nginx/vhosts/:rw
      - /workspace/service/nginx/logs/:/var/log/nginx/hss/:rw
    ports:
      - 8090:8090
    restart: always
    networks:
      - hss-network
  hss-boot:
    image: hss/hss-starter:2.1.1
    container_name: hss-boot
    privileged: true
    volumes:
      - /workspace/service/hss/:/app/conf/:rw
      - /workspace/service/hss/logs:/app/logs:rw
      - /workspace/service/hss/app.jar:/app/app.jar:rw
      - /var/upFiles:/var/upFiles:rw
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8081:8081
    restart: always
    networks:
      - hss-network
networks:
  hss-network:
    external: true

