spring:
  #json 时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  # 改为MySQL方言
  aop:
    proxy-target-class: true
  #配置freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    cache: false
    prefer-file-system-access: false
    template-loader-path:
      - classpath:/templates
  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher
  resource:
    static-locations: classpath:/static/,classpath:/public/

  # MySQL数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/hss?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#      username: root
#      password: Htkg123456
      url: jdbc:mysql://118.31.40.197:3306/hss?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      # 连接检测配置
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 监控配置
      filters: stat,wall
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          config:
            # 允许使用反引号
            identifierQuote: true
      # 连接池回收配置
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      # 打开PSCache
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 5s
    socket-timeout: 30s
  #redis 配置
  redis:
    database: 0
    host: 118.31.40.197
    port: 6379
    password: ''

#mybatis plus 设置
mybatis-plus:
  mapper-locations: [classpath*:com/hss/modules/**/xml/*Mapper.xml,classpath*:com/hss/core/modules/**/xml/*Mapper.xml]
  type-aliases-package: com.hss.modules.es7.domain
  configuration:
    map-underscore-to-camel-case: true
    database-id: mysql
    # 添加拦截器配置
#    interceptors:
#      - com.hss.core.config.SqlInterceptor
    call-setters-on-nulls: true
    # 缓存开启
    cache-enabled: true
    # 打印SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      # 主键类型
      id-type: ASSIGN_ID
      # 大写命名
      capital-mode: false
      # 表名下划线命名
      table-underline: true
      # 逻辑删除配置
      logic-delete-field: DELETED
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 数据库类型
      db-type: mysql

#Hss专用配置
jeecg:
  authMode: false
  authModeKey: HTKG
  safeMode: false
  uploadType: local
  domainUrl:
    pc: http://localhost:3100
    app: http://localhost:8051
  path:
    upload: /var/upFiles/
    voice: /var/upFiles/voice/
    ditu: /var/upFiles/ditu/
    webapp: /opt/webapp
    img:
      url: http://118.31.40.197:8081
  shiro:
    excludeUrls: /system/filesUtil/**,/category/**,/visual/**
#  minio:
#    minio_url: 118.31.40.197:9090
#    minio_name: minioadmin
#    minio_pass: minioadmin
#    bucketName: tests
minio:
  enable: true
  url: http://118.31.40.197
  port: 9000
  secure: false
  accessKey: SFANR7Z80HY0ATLCBBV3
  secretKey: nbbJICcmLCjhoKcmUjgQQeiJG5sfiQX9
  bucketName: tests

# 日志配置
logging:
  level:
    root: INFO
    com.hss: INFO
    org.springframework: INFO
    com.alibaba.druid: INFO
    com.mysql: INFO